previewsEnabled: true
services:
  - type: web
    plan: standard
    name: problem-finder-api
    env: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        generateValue: true
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
